# Generated by Django 3.0.6 on 2020-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_title', models.CharField(max_length=200, verbose_name='port title')),
                ('port_text', models.TextField(verbose_name='port text')),
                ('port_pub_date', models.DateTimeField(verbose_name='public date')),
                ('port_image', models.ImageField(default='media/main.jpg', upload_to='media/', verbose_name='port image')),
            ],
        ),
    ]
