# Generated by Django 3.0.6 on 2020-06-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default=23, upload_to='../media/blog/', verbose_name='blog image'),
            preserve_default=False,
        ),
    ]
